config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users, controllers: { registrations: 'registrations' }

  resources :twats do
    resources :comments
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'twats#index'
  put '/twat/:id/like', to: 'twats#like', as: 'like'
  post '/twat/:id/retwat', to: 'twats#retwat', as: 'retwat'
  post '/twat/:id/comment', to: 'twats#comment', as: 'comment_on_twat'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :twat
  validates :body, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :twat
  validates :user_id, uniqueness: { scope: :twat_id }

end

app/models/retwat.rb
class Retwat < ApplicationRecord
  belongs_to :twat
  belongs_to :user
end

app/models/twat.rb
class Twat < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :retwats, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates_length_of :twat, minimum: 2, maximum: 140, allow_blank: true

  def liked?(user)
    !!self.likes.find { |like| like.user_id == user.id }
  end

  def retwatted?(user)
    !!self.retwats.find { |retwat| retwat.user_id == user.id }
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates_presence_of :email, :password
  has_many :twats, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :retwats, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show; end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit; end

  # POST /comments or /comments.json
  def create
    @twat = Twat.find(params[:twat_id])
    @comment = @twat.comments.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @twat, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_comment
    @comment = Comment.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def comment_params
    params.require(:comment).permit(:body, :twat_id)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
  end

end

app/controllers/twats_controller.rb
class TwatsController < ApplicationController

  before_action :set_twat, only: %i[show edit update destroy like retwat]
  before_action :authenticate_user!, except: %i[index show]

  def comment(content)
    Comment.create(
      user_id: current_user.id,
      twat_id: @twat.id,
      content: content
    )
    redirect_to root_path, alert: 'Your comment has been successfully added!'
  end

  def retwat
    if @twat.retwatted?(current_user)
      redirect_to root_path, alert: 'Your\'ve already retwatted this from your account!'
    else
      original_twat = Twat.find(params[:id])

      @retwat = Twat.new(
        user_id: current_user.id,
        twat: "#{original_twat.twat}. Retwatted from:>> #{original_twat.user.username} <<",
        original_twat_id: original_twat.id
      )
      Retwat.create(
        user_id: current_user.id,
        twat_id: original_twat.id
      )
      if @retwat.save
        redirect_to root_path, alert: 'Retwatted!'
      else
        redirect_to root_path, alert: 'Can not retwatt'
      end
    end
  end

  def like
    if @twat.liked?(current_user)
      Like.all.find_by(user_id: current_user.id, twat_id: @twat.id).destroy
    else
      Like.create(user_id: current_user.id, twat_id: @twat.id)
    end
    redirect_to twats_url
  end

  # GET /twats or /twats.json
  def index
    @twats = Twat.all.order('created_at DESC')
    @twat = Twat.new
  end

  # GET /twats/1 or /twats/1.json
  def show; end

  # GET /twats/new
  def new
    @twat = current_user.twats.build
  end

  # GET /twats/1/edit
  def edit; end

  # POST /twats or /twats.json
  def create
    @twat = current_user.twats.build(twat_params)

    respond_to do |format|
      if @twat.save
        format.html { redirect_to root_path, notice: 'Twat was successfully created.' }
        format.json { render :show, status: :created, location: @twat }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @twat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /twats/1 or /twats/1.json
  def update
    respond_to do |format|
      if @twat.update(twat_params)
        format.html { redirect_to @twat, notice: 'Twat was successfully updated.' }
        format.json { render :show, status: :ok, location: @twat }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @twat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /twats/1 or /twats/1.json
  def destroy
    retwat = Retwat.all.find_by(user_id: current_user.id, twat_id: @twat.original_twat_id)
    retwat.destroy unless retwat.nil?
    @twat.destroy
    respond_to do |format|
      format.html { redirect_to twats_url, notice: 'Twat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_twat
    @twat = Twat.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def twat_params
    params.require(:twat).permit(:twat)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/twats_helper.rb
module TwatsHelper
end

app/views/comments/_form.html.erb
<%= simple_form_for(@comment) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :body %>
    <%= f.input :twat_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>Twat</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.body %></td>
        <td><%= comment.twat_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Twat:</strong>
  <%= @comment.twat_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twatter</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<% if flash[:notice] %>
  <div class="notification is-primary global-notification">
    <p class="notice">
      <%= notice %></p>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="notification is-danger global-notification">
    <p class="alert">
      <%= alert %></p>
  </div>
<% end %>
<nav class="navbar is-info">
  <div class="navbar-brand">
    <%= link_to root_path, class: "navbar-item" do %>
      <h1 class="title is-5">Twatter</h1>
    <% end %>
    <div class="navbar-burger burger" data-target="navbarExample">
      <span></span>
      <span></span>
      <span></span>
    </div>
  </div>

  <div id="navbarExample" class="navbar-menu">
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="field is-grouped">
          <p class="control">
            <%= link_to 'New Twat', root_path, class: "button is-info is-inverted" %>
          </p>
          <% if user_signed_in? %>
            <p class="control">
              <%= link_to current_user.name, edit_user_registration_path, class: "button is-info" %>
            </p>
            <p>
              <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "button is-info" %>
            </p>
          <% else %>
            <p class="control">
              <%= link_to 'Sign In', new_user_session_path, class: "button is-info" %>
            </p>
            <p class="control">
              <%= link_to 'Sign Up', new_user_registration_path, class: "button is-info" %>
            </p>
          <% end %>
        </div>
      </div>
    </div>
  </div>

</nav>

<%= yield %>
</body>
</html>

app/views/twats/_feed.html.erb
<div class="column is-half">
  <% if user_signed_in? %>
    <article class="media box">
      <figure class="media-left">
        <p class="image is-64x64">
          <%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name) %>
        </p>
      </figure>
      <div class="media-content">
        <%= render 'twats/form' %>
      </div>
    </article>
  <% end %>

  <% @twats.each do |twat| %>
    <div class="box">
      <article class="media">
        <div class="media-left">
          <figure class="image is-64x64">
            <%= gravatar_image_tag(twat.user.email, size: 64, alt: twat.user.name) %>
          </figure>
        </div>
        <div class="media-content">
          <div class="content">
            <strong><%= twat.user.name %></strong> <br/>
            <small><%= twat.user.username %></small><br/>
            <p><%= twat.twat %></p>
          </div>
          <nav class="level">
            <div class="level-left is-mobile">
              <% if user_signed_in? %>
                <%= link_to like_path(twat), method: :put, class: "level-item" do %>

                  <%= twat.likes.count %>
                  <span class="icon">
                <i class="fa fa-thumbs-up" aria-hidden="true"></i>
              </span>
                <% end %>
                <%= link_to retwat_path(twat), method: :post, class: "level-item" do %>

                  <%= twat.retwats.count %>
                  <span class="icon">
               <i class="fa fa-retweet" aria-hidden="true"></i>
              </span>
                <% end %>
                <%= link_to twat, class: "level-item" do %>

                  <%= twat.comments.count %>
              <span class="icon">
                <i class="fa fa-comment" aria-hidden="true"></i>
              </span>
                <% end %>
                <% if twat.user.id == current_user.id %>
                  <%= link_to edit_twat_path(twat), class: "level-item" do %>
             <span class="icon">
                <i class="fa fa-pencil" aria-hidden="true"></i>
              </span>
                  <% end %>
                  <%= link_to twat, method: :delete, data: { confirm: "Are U sure u want to delete this?" } do %>
             <span class="icon">
                <i class="fa fa-trash-o" aria-hidden="true"></i>
              </span>
                  <% end %>
                <% end %>
              <% else %>
                <%= twat.likes.count %>
                <span class="icon">
                <i class="fa fa-thumbs-up" aria-hidden="true"></i>
              </span>
                <%= twat.retwats.count %>
                <span class="icon">
               <i class="fa fa-retweet" aria-hidden="true"></i>
              </span>
              <% end %>
            </div>
          </nav>
        </div>
      </article>
    </div>
  <% end %>
</div>

app/views/twats/_form.html.erb
<%= simple_form_for(@twat) do |f| %>
  <%= f.error_notification %>
  <div class="field">
    <div class="control">
      <%= f.input :twat, label: "Twat about it",
                  input_html: { class: "textarea" },
                  wrapper: false, label_html: { class: "label" },
                  placeholder: "Compose a new twat...",
                  autofocus: true %>
    </div>
  </div>
  <%= f.button :submit, class: "button is-info" %>
<% end %>

app/views/twats/_profile.html.erb
<div class="column is-one-quarter">
  <nav class="panel">
    <p class="panel-heading">Profile</p>
    <div class="panel-block">
      <article class="media">
        <div class="media-left">
          <figure class="image is-64x64">
            <%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name) %>
          </figure>
        </div>
        <div class="media-content">
          <div class="content">
            <p>
              <strong><%= current_user.name %></strong> <br>
              <small><%= current_user.username %></small>
            </p>
          </div>
        </div>
      </article>
    </div>
    <div class="panel-block">
      <div class="level is-mobile">
        <div class="level-item has-centred-text">
          <div>
            <p class="heading">Twats</p>
            <p class="title is-6">
              <%= current_user.twats.count %></p>
          </div>
        </div>
        <div class="level-item has-centred-text">
          <div>
            <p class="heading">Following</p>
            <p class="title is-6">123</p>
          </div>
        </div>
        <div class="level-item has-centred-text">
          <div>
            <p class="heading">Followers</p>
            <p class="title is-6">542k</p>
          </div>
        </div>
      </div>
    </div>
  </nav>
</div>

app/views/twats/_trends.html.erb
<div class="column is-one-quarter">
  <nav class="panel">
    <p class="panel-heading">
      Trends
    </p>
    <a href="" class="panel-block">Trends 1</a>
    <a href="" class="panel-block">Trends 2</a>
    <a href="" class="panel-block">Trends 3</a>
    <a href="" class="panel-block">Trends 4</a>
    <a href="" class="panel-block">Trends 5</a>
    <a href="" class="panel-block">Trends 6</a>
  </nav>
</div>

app/views/twats/_who-to-follow.html.erb
<div class="column">
  <nav class="panel">
    <p class="panel-heading">Who to Follow</p>

    <div class="panel-block">
      <article class="media">
        <div class="media-left">
          <figure class="image is-32x32">
            <img src="https://bulma.io/images/placeholders/64x64.png">
          </figure>
        </div>
        <div class="media-content">
          <div class="content">
            <strong>John Smith</strong>
            <small>@johnSmith</small>
          </div>
        </div>
      </article>
    </div>

    <div class="panel-block">
      <article class="media">
        <div class="media-left">
          <figure class="image is-32x32">
            <img src="https://bulma.io/images/placeholders/64x64.png">
          </figure>
        </div>
        <div class="media-content">
          <div class="content">
            <strong>John Smith</strong>
            <small>@johnSmith</small>
          </div>
        </div>
      </article>
    </div>
  </nav>
</div>

app/views/twats/edit.html.erb
<div class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-half">
        <h1 class="title">Editing Twat</h1>
        <%= render 'form', twat: @twat %>
      </div>
    </div>
  </div>
</div>

<nav class="navbar is-fixed-bottom">
  <div class="navbar-menu">
    <div class="navbar-item">
      <div class="field is-grouped">
        <p class="control">
          <%= link_to 'Cancel', twats_path, class: "button is-dark" %>
        </p>
      </div>
    </div>
  </div>
</nav>

app/views/twats/index.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
      <% if user_signed_in? %>
        <%= render 'profile' %>
      <% else %>
        <%= render 'trends' %>
      <% end %>

      <%= render 'feed' %>
      <%= render 'who-to-follow' %>
    </div>
  </div>
</section>

app/views/twats/new.html.erb
<div class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-half">
        <h1 class="title">Create a new Twat</h1>
        <%= render 'form', twat: @twat %>
      </div>
    </div>
  </div>
</div>

<nav class="navbar is-fixed-bottom">
  <div class="navbar-menu">
    <div class="navbar-item">
      <div class="field is-grouped">
        <p class="control">
          <%= link_to 'Cancel', twats_path, class: "button is-dark" %>
        </p>
      </div>
    </div>
  </div>
</nav>

app/views/twats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Twat:</strong>
  <%= @twat.twat %>
</p>
<hr>
<small>Amount of Likes:</small>
<%= @twat.likes.count %>
<hr>
<small>Amount of Comments:</small>
<%= @twat.comments.count %>
<hr>
<small>Comments Content:</small>
<% @twat.comments.each do |comment| %>
  <p>
    <%= comment.body %>
  </p>
<% end %>

<div class="card my-1">
  <div class="card-body">
    <p class="font-weight-bold">Comments</p>
    <%= form_with(model: [@twat, @twat.comments.build]) do |f| %>
      <div class="form-group">
        <%= f.label 'New comment' %>
        <%= f.text_area :body, class: 'form-control' %>
      </div>
      <%= f.submit 'Submit', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

<%= link_to 'Edit', edit_twat_path(@twat) %> |
<%= link_to 'Back', twats_path %>